// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDance returns the embedded CollectionSpec for dance.
func loadDance() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DanceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dance: %w", err)
	}

	return spec, err
}

// loadDanceObjects loads dance and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*danceObjects
//	*dancePrograms
//	*danceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDanceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDance()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// danceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type danceSpecs struct {
	danceProgramSpecs
	danceMapSpecs
	danceVariableSpecs
}

// danceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type danceProgramSpecs struct {
	HandleExecveTp *ebpf.ProgramSpec `ebpf:"handle_execve_tp"`
	HandleOpenatTp *ebpf.ProgramSpec `ebpf:"handle_openat_tp"`
}

// danceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type danceMapSpecs struct {
	RbEvent *ebpf.MapSpec `ebpf:"rb_event"`
}

// danceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type danceVariableSpecs struct {
}

// danceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDanceObjects or ebpf.CollectionSpec.LoadAndAssign.
type danceObjects struct {
	dancePrograms
	danceMaps
	danceVariables
}

func (o *danceObjects) Close() error {
	return _DanceClose(
		&o.dancePrograms,
		&o.danceMaps,
	)
}

// danceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDanceObjects or ebpf.CollectionSpec.LoadAndAssign.
type danceMaps struct {
	RbEvent *ebpf.Map `ebpf:"rb_event"`
}

func (m *danceMaps) Close() error {
	return _DanceClose(
		m.RbEvent,
	)
}

// danceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDanceObjects or ebpf.CollectionSpec.LoadAndAssign.
type danceVariables struct {
}

// dancePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDanceObjects or ebpf.CollectionSpec.LoadAndAssign.
type dancePrograms struct {
	HandleExecveTp *ebpf.Program `ebpf:"handle_execve_tp"`
	HandleOpenatTp *ebpf.Program `ebpf:"handle_openat_tp"`
}

func (p *dancePrograms) Close() error {
	return _DanceClose(
		p.HandleExecveTp,
		p.HandleOpenatTp,
	)
}

func _DanceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dance_bpf.o
var _DanceBytes []byte
